GET http://localhost:3001/libro
#######

GET http://localhost:3001/libro/1

#######
POST http://localhost:3001/libro
Content-Type: application/json

{
    "id": 1,
    "titulo": "libro 1",
    "autor": "Gomez",
    "serie": "Arquitectura de Datos",
    "isbn13": "24",
    "categorias": "",
    "encuadernacion": "",
    "imagenPortadaUrl": "",
    "vecesReservado": 1,
    "available": true
}

######

PUT http://localhost:3001/libro
Content-Type: application/json

{
    "id": 1,
    "titulo": "libro 1",
    "autor": "Gomez",
    "serie": "Arquitectura de Datos",
    "isbn13": "24",
    "categorias": "",
    "encuadernacion": "",
    "imagenPortadaUrl": "",
    "vecesReservado": 1,
    "available": true
}

######
DELETE http://localhost:3001/libro/1