GET https://ggranda-20232-prograweb-as-api.azurewebsites.net/reserva
#######

GET https://ggranda-20232-prograweb-as-api.azurewebsites.net/reserva/1

#######
POST https://ggranda-20232-prograweb-as-api.azurewebsites.net/reserva
Content-Type: application/json

{
    "id": 1,
    "idUsuario": 1,
    "idLibro": 1,
    "fechaReserva": "2023-11-29 14:39:28.204-05",
    "fechaDevolucion": "2023-11-29 14:39:28.204-05",
    "estado": "1"
}

######

PUT https://ggranda-20232-prograweb-as-api.azurewebsites.net/reserva
Content-Type: application/json

{
    "id": 1,
    "idUsuario": 1,
    "idLibro": 1,
    "fechaReserva": "29/11/2023",
    "fechaDevolucion": "29/11/2023",
    "estado": "1"
}

######
DELETE https://ggranda-20232-prograweb-as-api.azurewebsites.net/reserva/1

#########
GET https://ggranda-20232-prograweb-as-api.azurewebsites.net/reserva/findAllComplete