GET http://localhost:3001/reserva
#######

GET http://localhost:3001/reserva/1

#######
POST http://localhost:3001/reserva
Content-Type: application/json

{
    "id": 1,
    "idUsuario": 1,
    "idLibro": 1,
    "fechaReserva": "2023-11-29 14:39:28.204-05",
    "fechaDevolucion": "2023-11-29 14:39:28.204-05",
    "estado": "1"
}

######

PUT http://localhost:3001/reserva
Content-Type: application/json

{
    "id": 1,
    "idUsuario": 1,
    "idLibro": 1,
    "fechaReserva": "29/11/2023",
    "fechaDevolucion": "29/11/2023",
    "estado": "1"
}

######
DELETE http://localhost:3001/reserva/1