GET https://ggranda-20232-prograweb-as-api.azurewebsites.net/tipoDoc
#######

GET https://ggranda-20232-prograweb-as-api.azurewebsites.net/tipoDoc/1

#######
POST https://ggranda-20232-prograweb-as-api.azurewebsites.net/tipoDoc
Content-Type: application/json

{
    "id": 2,
    "nombre": "Pasaporte"
}

######

PUT https://ggranda-20232-prograweb-as-api.azurewebsites.net/tipoDoc
Content-Type: application/json

{
    "id": 2,
    "nombre": "Pasaporte"
}

######
DELETE https://ggranda-20232-prograweb-as-api.azurewebsites.net/tipoDoc/1