GET https://ggranda-20232-prograweb-as-api.azurewebsites.net/tipoUsuario
#######

GET https://ggranda-20232-prograweb-as-api.azurewebsites.net/tipoUsuario/1

#######
POST https://ggranda-20232-prograweb-as-api.azurewebsites.net/tipoUsuario
Content-Type: application/json

{
    "id": 2,
    "nombre": "Administrador"
}

######

PUT https://ggranda-20232-prograweb-as-api.azurewebsites.net/tipoUsuario
Content-Type: application/json

{
    "id": 1,
    "nombre": "Alumno"
}

######
DELETE https://ggranda-20232-prograweb-as-api.azurewebsites.net/tipoUsuario/2