GET http://localhost:3001/usuario
#######

GET http://localhost:3001/usuario/1

#######
POST http://localhost:3001/usuario
Content-Type: application/json

{
    "id": 1,
    "nombres": "Pedro Javier",
    "apellidos": "Gomez Zevallos",
    "fotoUrl": "urldefoto",
    "tipoUsuario": 1,
    "idTipoDoc": 1,
    "nroDoc": "24384859",
    "correo": "pedro@gmail.com",
    "contrasena": "12345",
    "idioma": "español",
    "prefijo": "nose",
    "color": "rojo"
}

######

PUT http://localhost:3001/usuario
Content-Type: application/json

{
    "id": 1,
    "nombres": "Pedro Javier",
    "apellidos": "Gomez Zevallos",
    "fotoUrl": "urldefoto",
    "tipoUsuario": 1,
    "idTipoDoc": 1,
    "nroDoc": "24384859",
    "correo": "pedro@gmail.com",
    "contrasena": "12345",
    "idioma": "español",
    "prefijo": "nose",
    "color": "rojo"
}

######
DELETE http://localhost:3001/usuario/1