GET https://ggranda-20232-prograweb-as-api.azurewebsites.net/usuario
#######

GET https://ggranda-20232-prograweb-as-api.azurewebsites.net/usuario/1

#######
POST https://ggranda-20232-prograweb-as-api.azurewebsites.net/usuario
Content-Type: application/json

{
    "id": 1,
    "nombres": "George Patrick",
    "apellidos": "Granda Zapata",
    "fotoUrl": "https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2Ftfu8ilrr1w6a1.png",
    "tipoUsuario": 2,
    "idTipoDoc": 1,
    "nroDoc": "24384859",
    "correo": "george@gmail.com",
    "contrasena": "12345",
    "idioma": "español",
    "prefijo": "SHE/HER",
    "color": "rojo"
}

######

PUT https://ggranda-20232-prograweb-as-api.azurewebsites.net/usuario
Content-Type: application/json

{
    "id": 1,
    "nombres": "Pedro Javier",
    "apellidos": "Gomez Zevallos",
    "fotoUrl": "urldefoto",
    "tipoUsuario": 1,
    "idTipoDoc": 1,
    "nroDoc": "24384859",
    "correo": "pedro@gmail.com",
    "contrasena": "12345",
    "idioma": "español",
    "prefijo": "nose",
    "color": "rojo"
}

######
DELETE https://ggranda-20232-prograweb-as-api.azurewebsites.net/usuario/1